externalImagePath: home/ssm-user/seb44_main_026/images/

cloud:
  aws:
    credentials:
      access-key: AKIA3MJJGMPCERYKC2XZ
      secret-key: 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
    s3:
      bucketName: tourmatebucket
    region:
      static: ap-northeast-2 # 리전 정보
    stack:
      auto: false
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: username
    password: password
  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE

jwt:
  key: jasdfasfd1312345351354314560984745
  access-token-expiration-minutes: 120
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: admin@gmail.com
server:
  port: 8080