externalImagePath: home/ssm-user/seb44_main_026/images/
spring:
  prifiles:
    active: gcp,mysql
  #mvc:
  #  static-path-pattern: /images/**
  #resources:
  #  static-locations: file:${externalImagePath}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

    open-in-view: false

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        show_sql: true
  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:greennare-9e6b24e727ac.json
        project-id: greennare
        bucket: greennare-bucket-1
      sql:
        instance-conncetion-name: greennare:asia-northeast3:greennare-db
        database-name: greennare


  redis:
    cache:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql:///greennare?cloudSqlInstance=greennare:asia-northeast3:greennare-db&socketFactory=com.google.cloud.sql.mysql.SocketFactory
  #  url: jdbc:mysql://34.64.148.174:3306/greennare?serverTimezone=Asia/Seoul
    username: cloudrun
    password: cloudrun
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  sql:
    init:
    #schema-locations: classpath*:db/h2/schema.sql
    #data-locations: classpath*:db/h2/data.sql
  #  application:
  #    name: monitoring
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE

jwt:
  key: jasdfasfd1312345351354314560984745
  access-token-expiration-minutes: 120
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: admin@gmail.com
server:
  port: 8080
#management:
#  endpoint:
#    metrics:
#      enabled: true
#    prometheus:
#      enabled: true

# endpoints:
#    web:
#      exposure:
#        include: health, info, metrics, prometheus

# metrics:
#    tags:
#      application: ${spring.application.name}
