steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/greennare/greennare-cloud-run:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/greennare/greennare-cloud-run:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'greennare-cloud-run'
      - '--image'
      - 'gcr.io/greennare/greennare-cloud-run:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
      - '--add-cloudsql-instances'
      - 'greennare:asia-northeast3:greennare-db'
      - '--allow-unauthenticated'
      - '--platform'
      - 'managed'
      - '--update-env-vars'
      - 'INSTANCE_CONNECTION_NAME=greennare:asia-northeast3:greennare-db,DB_NAME=greennare,DB_USER=cloudrun,DB_PASSWORD=cloudrun'
      - '--service-account'
      - '24886443169-compute@developer.gserviceaccount.com'
