steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/greennare/greennare-cloud-run:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/greennare/greennare-cloud-run:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'greennare-cloud-run'
      - '--image'
      - 'gcr.io/greennare/greennare-cloud-run:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'
images:
  - 'gcr.io/greennare/greennare-cloud-run:$COMMIT_SHA'